### ISSUE TITLE
Is there any source code for ICS3Fuzzer?

### ISSUE THREAD

**Issue by Putinspudding** [boofish/ICS3Fuzzer#1]
I've rencently read your thesis on ACSAC, I would like to test it on TIA portal and simatic manager.

**Comment by boofish** [comment]
Thanks for your interest, I will upload the code these days and along with some tutorials.

**Comment by Putinspudding** [comment]
Thanks, for doing me a great favor.

**Comment by Parvin555** [comment]
Hello, I went through the code but couldn't understand the fuzzing algorithm. Is the fuzzing mechanism based on the Boofuzz, or after extracting the semantics using dispatcher, you are running your own algorithm? 

I want to Fuzz the IEC-104 (non-proprietary) protocol. Is there any way to do this?

**Comment by boofish** [comment]
> 

Hi, ICS3Fuzzer is designed to fuzz protocol implementated in supervisory software, who plays on a client role in the communication, and equipped with heavy GUIs. The fuzzing mechanism is in dispather.

For IEC-104, it can be implementated in the sever role (provide with service) or the client role (equipped with GUI). 
What are you going to fuzz? 
For server role, you can dirrectly use Boofuzz or Sulley to write some fuzzing templates, which is not the scope of ICS3Fuzzer.

**Comment by boofish** [comment]
> Hello, I went through the code but couldn't understand the fuzzing algorithm. Is the fuzzing mechanism based on the Boofuzz, or after extracting the semantics using dispatcher, you are running your own algorithm?
> 
> I want to Fuzz the IEC-104 (non-proprietary) protocol. Is there any way to do this?

Hi, ICS3Fuzzer is designed to fuzz protocol implementated in supervisory software, who plays on a client role in the communication, and equipped with heavy GUIs. The fuzzing mechanism is in dispather.

For IEC-104, it can be implementated in the sever role (provide with service) or the client role (equipped with GUI).
What are you going to fuzz?
For server role, you can dirrectly use Boofuzz or Sulley to write some fuzzing templates, which is not the scope of ICS3Fuzzer.

**Comment by Parvin555** [comment]
I'm trying to fuzz basic protocols like Modbus/TCP, CIP, etc. 

What do you mean by heavy GUIs?

**Comment by boofish** [comment]
> I'm trying to fuzz basic protocols like Modbus/TCP, CIP, etc.
In my understanding, generally fuzzing Modbus/TCP, CIP service is not the scope of ICS3Fuzzer.
There are many existing work covering Modbus/TCP, e.g., Boofuzz,  Polar: Function code aware fuzz testing of ics protocol, ICS protocol fuzzing: Coverage guided packet crack and generation. 

> What do you mean by heavy GUIs?
Heavy GUIs means the protocol implementation coupled with many GUIs, e.g., Buttons, Menus, Checkboxs, etc.
